<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NotifyMessages.Worker-7e940f66-6bce-4188-9594-aa51902aa2df</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotifyMessages.Application\NotifyMessages.Application.csproj" />
    <ProjectReference Include="..\NotifyMessages.Infrastructure\NotifyMessages.Infrastructure.csproj" />
  </ItemGroup>
</Project>
