// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyMessages.Infrastructure.Persistence;

#nullable disable

namespace NotifyMessages.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("NotifyMsg")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotifyMessages.Domain.Entities.MessageDispatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTEXT_DATA_JSON");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int")
                        .HasColumnName("CURRENT_STATUS");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_LOG");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EXTERNAL_ID");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IDEMPOTENCY_KEY");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROCESSED_AT");

                    b.Property<string>("RecipientContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RECIPIENT_CONTACT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RECIPIENT_NAME");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("RETRY_COUNT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TEMPLATE_ID");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TENANT_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageDispatch_IdempotencyKey");

                    b.HasIndex("CurrentStatus", "CreatedAt")
                        .HasDatabaseName("IX_MessageDispatch_QueueProcessing");

                    b.ToTable("MESSAGE_DISPATCH", "NotifyMsg");
                });

            modelBuilder.Entity("NotifyMessages.Domain.Entities.MessageDispatchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("DispatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("DISPATCH_ID");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EVENT_DATE");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EVENT_TYPE");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVIDER_RESPONSE");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId")
                        .HasDatabaseName("IX_MessageDispatchEvent_DispatchId");

                    b.ToTable("MESSAGE_DISPATCH_EVENTS", "NotifyMsg");
                });

            modelBuilder.Entity("NotifyMessages.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("CHANNEL");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ExternalTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("EXTERNAL_TEMPLATE_ID");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HTML_BODY");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int?>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("LIST_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int")
                        .HasColumnName("PROVIDER_TYPE");

                    b.Property<string>("SenderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENDER_NAME");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SUBJECT");

                    b.Property<string>("TextBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TEXT_BODY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.Property<bool>("UseCampaignMode")
                        .HasColumnType("bit")
                        .HasColumnName("USE_CAMPAIGN_MODE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Template_Name");

                    b.ToTable("TEMPLATE", "NotifyMsg");
                });

            modelBuilder.Entity("NotifyMessages.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("API_KEY_HASH");

                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOCUMENT_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_ApiKeyHash")
                        .HasFilter("[API_KEY_HASH] IS NOT NULL");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tenant_Name");

                    b.ToTable("TENANT", "NotifyMsg");
                });

            modelBuilder.Entity("NotifyMessages.Domain.Entities.TenantProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountSid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ACCOUNT_SID");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("API_KEY");

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTH_TOKEN");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BASE_URL");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DOMAIN");

                    b.Property<string>("FromNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FROM_NUMBER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit")
                        .HasColumnName("IS_GLOBAL");

                    b.Property<int?>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("LIST_ID");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int")
                        .HasColumnName("PROVIDER_TYPE");

                    b.Property<string>("SecretName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SECRET_NAME");

                    b.Property<string>("SenderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENDER_NAME");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TENANT_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderType")
                        .HasDatabaseName("IX_TenantProviderConfig_Tenant_Provider");

                    b.ToTable("TENANT_PROVIDER_CONFIG", "NotifyMsg");
                });

            modelBuilder.Entity("NotifyMessages.Domain.Entities.MessageDispatchEvent", b =>
                {
                    b.HasOne("NotifyMessages.Domain.Entities.MessageDispatch", null)
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
