<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotifyMessages.Api\NotifyMessages.Api.csproj" />
    <ProjectReference Include="..\NotifyMessages.Application\NotifyMessages.Application.csproj" />
    <ProjectReference Include="..\NotifyMessages.Domain\NotifyMessages.Domain.csproj" />
    <ProjectReference Include="..\NotifyMessages.Infrastructure\NotifyMessages.Infrastructure.csproj" />
    <ProjectReference Include="..\NotifyMessages.Worker\NotifyMessages.Worker.csproj" />
  </ItemGroup>

</Project>