USE [NotifyMsgDB]
GO
/****** Object:  Table [dbo].[MESSAGEFLOW_DISPATCH]    Script Date: 26/05/2026 13:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESSAGEFLOW_DISPATCH](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TENANT_ID] [int] NOT NULL,
	[TEMPLATE_ID] [int] NOT NULL,
	[IDEMPOTENCY_KEY] [varchar](100) NOT NULL,
	[EXTERNAL_ID] [varchar](100) NULL,
	[RECIPIENT_NAME] [varchar](100) NULL,
	[RECIPIENT_CONTACT] [varchar](100) NULL,
	[CONTEXT_DATA_JSON] [nvarchar](max) NULL,
	[CURRENT_STATUS] [varchar](20) NOT NULL,
	[CREATED_AT] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MESSAGEFLOW_DISPATCH_EVENTS]    Script Date: 26/05/2026 13:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESSAGEFLOW_DISPATCH_EVENTS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DISPATCH_ID] [bigint] NOT NULL,
	[EVENT_TYPE] [varchar](50) NOT NULL,
	[EVENT_DATE] [datetime] NOT NULL,
	[PROVIDER_RESPONSE] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MESSAGEFLOW_TEMPLATE]    Script Date: 26/05/2026 13:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESSAGEFLOW_TEMPLATE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TENANT_ID] [int] NOT NULL,
	[CHANNEL] [varchar](20) NOT NULL,
	[TRIGGER_TYPE_ID] [int] NOT NULL,
	[SUBJECT] [varchar](200) NULL,
	[BODY_CONTENT] [nvarchar](max) NOT NULL,
	[AI_TONE_INSTRUCTION] [varchar](200) NULL,
	[RETRY_POLICY] [varchar](50) NULL,
	[REQUIRED_VARS_JSON] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAAS_TENANT]    Script Date: 26/05/2026 13:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAAS_TENANT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[DOCUMENT_ID] [varchar](20) NULL,
	[ACTIVE] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DISPATCH_IDEMPOTENCY]    Script Date: 26/05/2026 13:41:42 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_DISPATCH_IDEMPOTENCY] ON [dbo].[MESSAGEFLOW_DISPATCH]
(
	[IDEMPOTENCY_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_DISPATCH_STATUS_DATE]    Script Date: 26/05/2026 13:41:42 ******/
CREATE NONCLUSTERED INDEX [IX_DISPATCH_STATUS_DATE] ON [dbo].[MESSAGEFLOW_DISPATCH]
(
	[CURRENT_STATUS] ASC,
	[CREATED_AT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[SAAS_TENANT] ADD  DEFAULT ((1)) FOR [ACTIVE]
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH]  WITH CHECK ADD  CONSTRAINT [FK_DISPATCH_TEMPLATE] FOREIGN KEY([TEMPLATE_ID])
REFERENCES [dbo].[MESSAGEFLOW_TEMPLATE] ([ID])
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH] CHECK CONSTRAINT [FK_DISPATCH_TEMPLATE]
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH]  WITH CHECK ADD  CONSTRAINT [FK_DISPATCH_TENANT] FOREIGN KEY([TENANT_ID])
REFERENCES [dbo].[SAAS_TENANT] ([ID])
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH] CHECK CONSTRAINT [FK_DISPATCH_TENANT]
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH_EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_DISPATCH] FOREIGN KEY([DISPATCH_ID])
REFERENCES [dbo].[MESSAGEFLOW_DISPATCH] ([ID])
GO
ALTER TABLE [dbo].[MESSAGEFLOW_DISPATCH_EVENTS] CHECK CONSTRAINT [FK_EVENTS_DISPATCH]
GO
ALTER TABLE [dbo].[MESSAGEFLOW_TEMPLATE]  WITH CHECK ADD  CONSTRAINT [FK_TEMPLATE_TENANT] FOREIGN KEY([TENANT_ID])
REFERENCES [dbo].[SAAS_TENANT] ([ID])
GO
ALTER TABLE [dbo].[MESSAGEFLOW_TEMPLATE] CHECK CONSTRAINT [FK_TEMPLATE_TENANT]
GO
